### ISSUE TITLE
Digital Ocean Ingress Addition 

### ISSUE THREAD

**Issue by alexbeattie42** [livekit/livekit-helm#16]
I am going to be deploying LiveKit to Digital Ocean Kubernetes. I will be doing some development on the Helm chart to support Digital Ocean Nginx Ingress. I'd be happy to put up a pull request to add support for Digital Ocean Kubernetes Ingress to this repo once I get it working if that is desired.

**Comment by davidzhao** [comment]
@alexbeattie42 that would be amazing. We would love to support Digital Ocean with the Helm set up, but just haven't gotten around to it.

Please open a PR when you manage to get it to work. I appreciate it!

**Comment by alexbeattie42** [comment]
I'm not quite sure how the docs are maintained but [this](https://docs.livekit.io/deploy/ports-firewall) documentation is missing the UDP port range 50000-60000 for the digital ocean setup

**Comment by davidzhao** [comment]
Oh do you mean the screenshot? that's by no means comprehensive. The table above contains the ports that need to be included.
