### ISSUE TITLE
K8s v1beta1 ingress is deprecated

### ISSUE THREAD

**Issue by alexbeattie42** [livekit/livekit-helm#18]
networking.k8s.io/v1beta1 is deprecated in the v1.19 release of kubernetes and will be unavailable in the v1.22+ release. [This](https://kubernetes.io/docs/reference/using-api/deprecation-guide/) documentation specifies this. I can put up a pull request that I know works for digital ocean but I would not be able to verify it with other cluster configurations.

**Comment by davidzhao** [comment]
@alexbeattie42, that would be fantastic. With v1.18 getting phased out by cloud providers, we should be in good shape to move to the new API introduced in v1.19. It'd be great if you could open a PR!
