### ISSUE TITLE
Tolerations aren't set for Daemonset

### ISSUE THREAD

**Issue by loreskovic** [livekit/livekit-helm#23]
The Helm chart allows for tolerations to be added to the deployment, and this works correctly, but the same tolerations aren't added to the Daemonset.

**Comment by davidzhao** [comment]
@loreskovic that would make sense to have.. If you are up for it, it'd be great to see a PR to improve this!

**Comment by davidzhao** [comment]
@loreskovic we've stopped using the daemonset, so this is no longer an issue.
