### ISSUE TITLE
Current helm charts doesn't work metrics exporter.

### ISSUE THREAD

**Issue by monkeydaichan** [livekit/livekit-helm#24]
Current helm charts doesn't work metrics exporter.

Reason
Promethes port doesn't open.

Tasks
- [x] Expose 6789 port in deployment.
- [x] Expose 6789 port in service.
- [x] Output config.yaml for metrics. How to setup it in prometheus.
- [x] Update values.yaml
- [ ] Update README

**Comment by monkeydaichan** [comment]
Hi, @davidzhao 
I improved helm chart for prometheus.  
How do I contribute??

Regards.

**Comment by davidzhao** [comment]
@monkeydaichan Please submit a PR!
