### ISSUE TITLE
Cloud this helm chart provide to custom path domain to connect ?

### ISSUE THREAD

**Issue by truonghdpk** [livekit/livekit-helm#43]
- Yub as title, for our architect live-kit in behind and proxy by Nginx, thus I would recommend using subpath to direct livekit server but when proxy is done, livekit reject connect to cause it doesn't support custom subpath to connect to 
How to solve the problem, for my reason it should custom subpath in livekit to support behind proxy !!

**Comment by davidzhao** [comment]
sorry, that is out of scope for this helm chart. you are welcome to fork it and add this as a feature in your fork.
