### ISSUE TITLE
Turn load balancer with external TLS

### ISSUE THREAD

**Issue by serhatperkmen** [livekit/livekit-helm#45]
Hi, is there any specific reason for the if statement for the below code?  

https://github.com/livekit/livekit-helm/blob/8f91315c7a38bf785226e3f069328aa4b55c17ac/livekit-server/templates/turnloadbalancer.yaml#L12-L15

I am deploying it behind a L4 load balancer where the TLS terminates. So that I set external_tls to true. 
Because of the if statement, the service is created as ClusterIP and [ExternalDNS](https://github.com/kubernetes-sigs/external-dns) is not adding a record to Route53.

In the previous version there was no if statement. That is added with [this](https://github.com/livekit/livekit-helm/commit/d53af31dbded4d0d5146291c7c70fa95647cee18) commit.

**Comment by davidzhao** [comment]
Which kubernetes provider are you using? With some providers, the load balancer created with a `Service` isn't always an L4 LB.

So instead we are making this more customizable for the user, you can place a custom Ingress in front of the service to configure that Ingress/LB.

**Comment by bmbferreira** [comment]
I'm also facing this issue. I want to terminate TLS at the load balancer.  I'm running on EKS with [aws load balancer controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller).

**Comment by bmbferreira** [comment]
If we want to make it more customisable for the user, IMO the type for the service should be parameterised:
https://github.com/livekit/livekit-helm/pull/49

**Comment by serhatperkmen** [comment]
Hi @davidzhao and @bmbferreira,

I am also running on EKS with AWS load balancer controller.
I strongly agree your PR @bmbferreira. The type should be loadBalancer.
