### ISSUE TITLE
Unable to download the chart for 1.3.2

### ISSUE THREAD

**Issue by weeezes** [livekit/livekit-helm#57]
Hi!

I noticed there's an issue with fetching the latest 1.3.2 version of the chart, example:

```
$ helm repo update
$ helm pull livekit/livekit-server --version 1.3.2
Error: fetch from s3 url=s3://livekit-helm/livekit-server-1.3.2.tgz: fetch object from s3: AccessDenied: Access Denied
	status code: 403, request id: P0YY34MK56C4DQWF, host id: 0rYDRlEotXf6lwdE7AmrEOSJHbH+FirwrwLkPfRhV5CaJHLYirkVYHSIVbwrhCUS5czqCRoBjWU=
Error: plugin "bin/helm-s3 download" exited with error
```

**Comment by danpe** [comment]
Same here 🙋🏻

**Comment by davidzhao** [comment]
Are you adding the S3 endpoint directly? That should only be done for the core team for publishing. Please use the public repo on CloudFront instead: `helm repo add livekit https://helm.livekit.io`

**Comment by furkanKotic** [comment]
It may have something to do with this issue. I also get this error after helm repo update: Error: failed to download "livekit/livekit-server"

**Comment by davidzhao** [comment]
I see the problem, it should be fixed now. sorry for the inconveniences!

**Comment by danpe** [comment]
Fixed
