### ISSUE TITLE
Cloudflare R2 support for Egress

### ISSUE THREAD

**Issue by anishmenon** [livekit/livekit-helm#68]
As i can se only 

`      case *livekit.S3Upload:
		return newS3Uploader(c)
	case *livekit.GCPUpload:
		return newGCPUploader(c)
	case *livekit.AzureBlobUpload:
		return newAzureUploader(c)
	case *livekit.AliOSSUpload:
		return newAliOSSUploader(c)`
		
		
Can we add Cloudflare R2 Support too ??

**Comment by davidzhao** [comment]
R2 is compatible with S3.
