### ISSUE TITLE
Support Kubernetes 1.26

### ISSUE THREAD

**Issue by p4block** [livekit/livekit-helm#74]
`autoscaling/v2beta1` is deprecated and the helmchart tried to generate it. I've modified the output yaml for the new spec manually:

```
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
(...)
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60

**Comment by davidzhao** [comment]
How did you generate the output YAML? It should already be generating `autoscaling/v2` for Kube > 1.23:

```
{{- if semverCompare ">=1.23-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: autoscaling/v2
{{- else }}
apiVersion: autoscaling/v2beta1
{{- end }}
```

**Comment by davidzhao** [comment]
If you are using `helm template`, please ensure you are passing in `--kube-version 1.26` to give it that context. I suspect that's what's happening here.
