### ISSUE TITLE
TURN with udp only throws error

### ISSUE THREAD

**Issue by lukasIO** [livekit/livekit-helm#8]
I wanted to try the UDP only approach for the turn server as mentioned in the docs [here](https://docs.livekit.io/guides/deploy#turnudp)

but I get the following error when trying to deploy with turn enabled and only a udp port set:
`execution error at (livekit-server/templates/deployment.yaml:97:27): tls secret required if turn enabled`

**Comment by davidzhao** [comment]
fixed in v0.13.1, let me know if this works for you.
